### ISSUE TITLE
New error:  raincloudy.exceptions.RainCloudyException

### ISSUE THREAD

**Issue by joseph85750** [vanstinator/raincloudy#30]
Apparently melnor made a change which appears to have broken the code.  I now get an exception, with the exact date when the error first occurred:

Exception occured: <class 'requests.exceptions.ConnectionError'> at Mon May 21 02:33:21 GMT 2019

**Comment by i-am-snappy** [comment]
I can confirm it is broken in Home Assistant too. I rolled back to a previous known working backup. Fault there too, so suspect as @joseph85750 states, Melnor have made a change. Let me know if you need any data from me.

**Comment by etymotic** [comment]
I too cannot use the component currently. 

Here is the log file from hass.io https://hastebin.com/wujeruhuqo.sql

```javascript
Wed Mar 27 2019 12:51:50 GMT-0400 (Eastern Daylight Time)
Error during setup of component raincloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raincloudy/helpers.py", line 37, in serial_finder
    result = regex.search(child.string).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/raincloud/__init__.py", line 101, in setup
    raincloud = RainCloudy(username=username, password=password)
  File "/usr/local/lib/python3.7/site-packages/raincloudy/core.py", line 59, in __init__
    self.login()
  File "/usr/local/lib/python3.7/site-packages/raincloudy/core.py", line 68, in login
    self._authenticate()
  File "/usr/local/lib/python3.7/site-packages/raincloudy/core.py", line 99, in _authenticate
    parsed_controller = serial_finder(self.html['home'])
  File "/usr/local/lib/python3.7/site-packages/raincloudy/helpers.py", line 48, in serial_finder
    'Could not find any valid controller or faucet')
raincloudy.exceptions.RainCloudyException: Could not find any valid controller or faucet
```

**Comment by tchellomello** [comment]
Hello guys, 
Thanks for reporting the problem. I'll try to take a look over the weekend to see what happened on the backend.

**Comment by riddertommie** [comment]
Hi Maybe this helps, and maybe not (then sorry!!!).

I have what looks like a similar problem:

https://github.com/home-assistant/hassio-build/issues/153

i hope it helps

**Comment by vanstinator** [comment]
I just got one of these _today_ and I'm taking a stab at identifying the issue here. Since I don't have any previous context of what the html of the page looked like I don't know for sure what's broken but it looks like this line: https://github.com/tchellomello/raincloudy/blob/master/raincloudy/helpers.py#L36

From what I can tell the ajax script change and it no longer contains the values you were looking for. I'm going to see if there's another easy way to extract the IDs with BeautifulSoup from the home page. If not maybe we can grab them off a different page.

**Comment by vanstinator** [comment]
So I'm thinking there are bigger changes afoot. The `POST /dajaxice/webserver.get_cu_and_fu_status/` endpoint signature has changed to `GET /get_cu_and_fu_status` and various attributes have changed. It's possible the structure of the response has changed as well because this function (https://github.com/tchellomello/raincloudy/blob/master/raincloudy/helpers.py#L51) is throwing type errors now.

**Comment by vanstinator** [comment]
The root issue has been fixed in version `0.0.6`.

PR has been submitted to HA: https://github.com/home-assistant/home-assistant/pull/22805

**Comment by joseph85750** [comment]
I'm still seeing the issue.  But is everyone else working fine?

 

    On Saturday, April 6, 2019, 1:30:54 PM MST, Justin Vanderhooft <notifications@github.com> wrote:  
 
 
Closed #30.

**Comment by etymotic** [comment]
joseph85750, working great for me. I think the fix was included in 0.92.1 or maybe it was 0.92.0. Which version of HA do you have?

**Comment by vanstinator** [comment]
Yeah. Fix rolled out in .92. If you're still having issues please post a log somewhere so I can take a look.

**Comment by joseph85750** [comment]
I just now downloaded the latest/greatest master.zip and still have the error:
requests.exceptions.HTTPError

I wrote my own script to check my devices.  What can I provide?

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=myIdHere&faucet_serial=mySerialHere

**Comment by vanstinator** [comment]
Please use the current issue #41 as this appears to be unrelated to this issue.
